"""Optional AI layer.

Everything in `scanner.py`, `duplicates.py`, `archives.py`, `planner.py`,
and `executor.py` works with zero AI involvement -- that's the trustworthy,
deterministic core. This module only adds a plain-English summary of the
findings, generated by Gemini, so the report reads like something a person
wrote instead of a wall of JSON.

If no GEMINI_API_KEY is set, `summarize()` returns None and the CLI falls
back to a plain-text summary -- the tool never *requires* an API key.
"""

from __future__ import annotations

import os

from .archives import ArchiveInfo
from .duplicates import DuplicateGroup


def _format_bytes(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.1f}{unit}"
        n /= 1024
    return f"{n:.1f}TB"


def summarize(
    duplicate_groups: list[DuplicateGroup],
    archives: list[ArchiveInfo],
    model: str = "gemini-3.5-flash",
) -> str | None:
    """Returns a short natural-language summary, or None if Gemini is unavailable."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return None

    try:
        from google import genai
    except ImportError:
        return None

    total_wasted = sum(g.wasted_bytes for g in duplicate_groups)
    facts = (
        f"- {len(duplicate_groups)} duplicate file group(s) found, "
        f"wasting approximately {_format_bytes(total_wasted)} of disk space.\n"
        f"- {len(archives)} archive/zip file(s) found "
        f"(entry counts: {[a.entry_count for a in archives if a.entry_count is not None]}).\n"
    )

    prompt = (
        "You are a file-organization assistant. Given these raw scan facts, "
        "write a short (3-5 sentence) plain-English summary for a non-technical "
        "user, plus one practical recommendation. Do not invent numbers beyond "
        "what's given.\n\nFacts:\n" + facts
    )

    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(model=model, contents=prompt)
        return response.text
    except Exception:
        # Network issues, quota errors, etc. -- fail soft, the report still works.
        return None
